//! Who is signed in, for HTML pages. Generated by `ocre g auth`.
//!
//! - `CurrentUser(user): CurrentUser` in a handler requires a signed-in user;
//!   other visitors are redirected to /login, then back to the page.
//! - `OptionalUser(user): OptionalUser` gives `Option<User>` (e.g. a menu).
//! - `sign_in` / `sign_out` change the session; the login, sign-up and
//!   magic-link handlers call them.
//!
//! The session (an encrypted cookie) holds only `user_id`. JSON clients use
//! `BearerUser` from src/auth_api.rs instead.

// Extractors and helpers for the app's own pages; not all are used yet.
#![allow(dead_code)]

use axum::{
    extract::FromRequestParts,
    http::{Method, Uri, request::Parts},
    response::{IntoResponse, Redirect, Response},
};
use ocre::{Ctx, Error, Result, Session};

use crate::models::user::{self, User};

/// Session key holding the signed-in user's id.
pub const USER_ID: &str = "user_id";
/// Session key holding the page to return to after logging in.
const RETURN_TO: &str = "return_to";

/// The signed-in user. Visitors are redirected to /login.
pub struct CurrentUser(pub User);

/// The signed-in user, if any.
pub struct OptionalUser(pub Option<User>);

impl FromRequestParts<Ctx> for OptionalUser {
    type Rejection = Error;

    async fn from_request_parts(parts: &mut Parts, ctx: &Ctx) -> Result<Self> {
        let session = Session::from_request_parts(parts, ctx).await?;
        match session.get::<i64>(USER_ID)? {
            Some(id) => Ok(Self(user::find(ctx, id).await?)),
            None => Ok(Self(None)),
        }
    }
}

impl FromRequestParts<Ctx> for CurrentUser {
    type Rejection = Response;

    async fn from_request_parts(parts: &mut Parts, ctx: &Ctx) -> std::result::Result<Self, Response> {
        match OptionalUser::from_request_parts(parts, ctx).await {
            Ok(OptionalUser(Some(user))) => Ok(Self(user)),
            Ok(OptionalUser(None)) => Err(to_login(parts, ctx).await.unwrap_or_else(IntoResponse::into_response)),
            Err(err) => Err(err.into_response()),
        }
    }
}

/// Redirects to /login, remembering the page for GET requests (a form
/// submission cannot be replayed after a redirect).
async fn to_login(parts: &mut Parts, ctx: &Ctx) -> Result<Response> {
    let session = Session::from_request_parts(parts, ctx).await?;
    if parts.method == Method::GET {
        session.insert(RETURN_TO, parts.uri.path_and_query().map_or("/", |path| path.as_str()))?;
    }
    session.flash("alert", "Please log in to continue.")?;
    Ok(Redirect::to("/login").into_response())
}

/// Signs `user` in and returns where to go next: the page that asked for a
/// login, or `/`. The session is emptied first (pending flash messages
/// stay), so nothing from before the login carries over.
pub fn sign_in(session: &Session, user: &User) -> Result<String> {
    let return_to = session.get::<String>(RETURN_TO)?.filter(|path| is_local_path(path));
    session.clear()?;
    session.insert(USER_ID, user.id)?;
    Ok(return_to.unwrap_or_else(|| "/".to_owned()))
}

/// Signs out: empties the session.
pub fn sign_out(session: &Session) -> Result<()> {
    session.clear()
}

/// `/account` yes; `//evil.example` or `https://...` no (open redirects).
fn is_local_path(path: &str) -> bool {
    path.starts_with('/') && !path.starts_with("//") && !path.starts_with("/\\")
}

/// `https://app.example.com`: scheme and host of the current request, for
/// links in emails. Cloudflare routes requests by host name, so this is always
/// one of the app's own hosts.
pub fn origin(uri: &Uri) -> String {
    let scheme = uri.scheme_str().unwrap_or("https");
    let host = uri.authority().map_or("localhost", |authority| authority.as_str());
    format!("{scheme}://{host}")
}
