-- Generated by `ocre g auth --oauth`: accounts at OAuth providers (GitHub,
-- Google) linked to users.
CREATE TABLE identities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    uid TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX index_identities_on_provider_and_uid ON identities (provider, uid);
CREATE INDEX index_identities_on_user_id ON identities (user_id);
