-- Generated by `ocre g auth`: API keys for `Authorization: Bearer <key>`.
-- Only SHA-256 digests are stored; the key is shown once, when created.
CREATE TABLE api_keys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    digest TEXT NOT NULL,
    last_used_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX index_api_keys_on_digest ON api_keys (digest);
CREATE INDEX index_api_keys_on_user_id ON api_keys (user_id);
