-- Generated by `ocre g auth`: single-use tokens emailed for password resets
-- and magic-link logins. Only SHA-256 digests are stored (ocre::token::digest).
CREATE TABLE auth_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- 'password_reset' or 'magic_link'
    purpose TEXT NOT NULL,
    digest TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX index_auth_tokens_on_digest ON auth_tokens (digest);
CREATE INDEX index_auth_tokens_on_user_id ON auth_tokens (user_id);
