-- Generated by `ocre g auth`. Emails are stored trimmed and lowercased
-- (src/models/user.rs); NOCASE makes lookups and uniqueness ignore case anyway.
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL COLLATE NOCASE,
    -- ocre::password digest (PBKDF2-HMAC-SHA256), never the password.
    password_digest TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX index_users_on_email ON users (email);
