-- Generated by `ocre g auth --db-sessions`: one row per signed-in device.
-- The session cookie carries a random token; only its SHA-256 digest is here.
CREATE TABLE user_sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    digest TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    last_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX index_user_sessions_on_digest ON user_sessions (digest);
CREATE INDEX index_user_sessions_on_user_id ON user_sessions (user_id);
