//! Sign-up and the account page (HTML). Generated by `ocre g auth`.

use askama::Template;
use axum::{
    Form, Router,
    extract::State,
    http::StatusCode,
    response::{Html, IntoResponse, Redirect, Response},
    routing::get,
};
use ocre::{Ctx, Error, FieldError, Flash, Result, Session, render};

use crate::{
    auth::{CurrentUser, sign_in},
    models::user::{self, NewUser, User},
};

pub fn routes() -> Router<Ctx> {
    Router::new().route("/signup", get(new).post(create)).route("/account", get(show))
}

#[derive(Template)]
#[template(path = "auth/signup.html")]
struct SignupView {
    email: String,
    errors: Vec<FieldError>,
}

#[derive(Template)]
#[template(path = "auth/account.html")]
struct AccountView {
    flash: Flash,
    user: User,
}

async fn new() -> Result<Html<String>> {
    render(&SignupView { email: String::new(), errors: vec![] })
}

async fn create(State(ctx): State<Ctx>, session: Session, Form(new): Form<NewUser>) -> Result<Response> {
    let email = new.email.clone();
    match user::create(&ctx, new).await {
        Ok(user) => {
            let next = sign_in(&session, &user)?;
            session.flash("notice", "Welcome! Your account is ready.")?;
            Ok(Redirect::to(&next).into_response())
        }
        Err(Error::Invalid(errors)) => {
            Ok((StatusCode::UNPROCESSABLE_ENTITY, render(&SignupView { email, errors })?).into_response())
        }
        Err(err) => Err(err),
    }
}

/// A protected page: `CurrentUser` redirects visitors to /login.
async fn show(CurrentUser(user): CurrentUser, flash: Flash) -> Result<Html<String>> {
    render(&AccountView { flash, user })
}
