//! User model: the `users` table. Generated by `ocre g auth`.
//!
//! Emails are stored trimmed and lowercased, so `Ada@Example.com` and
//! `ada@example.com` are one account. Passwords are stored as
//! `ocre::password` digests (PBKDF2); `password_digest` is never serialized.

use ocre::{Ctx, Error, Result, Validator, params};
use serde::{Deserialize, Serialize};

/// Shortest accepted password.
pub const MIN_PASSWORD_LENGTH: usize = 8;
/// Longest accepted password, to bound the work per request.
pub const MAX_PASSWORD_LENGTH: usize = 128;

/// A row of the `users` table.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct User {
    pub id: i64,
    pub email: String,
    #[serde(skip_serializing)]
    pub password_digest: String,
    pub created_at: String,
    pub updated_at: String,
}

/// Sign-up values, as typed (HTML form or JSON). Missing fields are empty,
/// so they fail validation with a message instead of a 400.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default)]
pub struct NewUser {
    pub email: String,
    pub password: String,
}

impl NewUser {
    /// Checks that need no database; `create` adds uniqueness.
    pub fn validate(&self) -> Validator {
        let mut v = Validator::new();
        let email = normalize_email(&self.email);
        if email.is_empty() {
            v.required("email", &email);
        } else {
            v.email("email", &email).max_length("email", &email, 254);
        }
        validate_password(&mut v, &self.password);
        v
    }
}

/// `" Ada@Example.COM "` -> `"ada@example.com"`.
pub fn normalize_email(email: &str) -> String {
    email.trim().to_lowercase()
}

/// Password rules, for sign-up and password changes.
pub fn validate_password(v: &mut Validator, password: &str) {
    v.min_length("password", password, MIN_PASSWORD_LENGTH).max_length("password", password, MAX_PASSWORD_LENGTH);
}

pub async fn find(ctx: &Ctx, id: i64) -> Result<Option<User>> {
    ctx.db()?.first("SELECT * FROM users WHERE id = ?1", params![id]).await
}

pub async fn find_by_email(ctx: &Ctx, email: &str) -> Result<Option<User>> {
    ctx.db()?.first("SELECT * FROM users WHERE email = ?1", params![normalize_email(email)]).await
}

/// Creates the user with a hashed password (one PBKDF2 run).
pub async fn create(ctx: &Ctx, new: NewUser) -> Result<User> {
    let db = ctx.db()?;
    let email = normalize_email(&new.email);
    let mut v = new.validate();
    v.check(
        "email",
        db.exists("SELECT 1 FROM users WHERE email = ?1 LIMIT 1", params![&email]).await?,
        "has already been taken",
    );
    v.finish()?;
    let password_digest = ocre::password::hash(&new.password).await?;
    db.first("INSERT INTO users (email, password_digest) VALUES (?1, ?2) RETURNING *", params![email, password_digest])
        .await?
        .ok_or_else(|| Error::internal("INSERT ... RETURNING returned no row"))
}

/// The user with this email and password, or `None`. An unknown email costs
/// the same PBKDF2 run as a wrong password, so response times do not reveal
/// which emails have accounts.
pub async fn authenticate(ctx: &Ctx, email: &str, password: &str) -> Result<Option<User>> {
    let Some(user) = find_by_email(ctx, email).await? else {
        ocre::password::hash(password).await?;
        return Ok(None);
    };
    let valid = ocre::password::verify(password, &user.password_digest).await?;
    Ok(valid.then_some(user))
}

/// Replaces the password (password reset). 422 when it breaks the rules.
pub async fn update_password(ctx: &Ctx, id: i64, password: &str) -> Result<()> {
    let mut v = Validator::new();
    validate_password(&mut v, password);
    v.finish()?;
    let password_digest = ocre::password::hash(password).await?;
    ctx.db()?
        .execute(
            "UPDATE users SET password_digest = ?1, updated_at = datetime('now') WHERE id = ?2",
            params![password_digest, id],
        )
        .await?;
    Ok(())
}
