//! `ocre g job`, `ocre g schedule` and the queues `ocre deploy` creates, run
//! through the real binary.

#[path = "../support/mod.rs"]
mod support;

use std::fs;

use serde_json::json;
use support::{Sandbox, text};

fn read(root: &std::path::Path, path: &str) -> String {
    fs::read_to_string(root.join(path)).unwrap()
}

#[test]
fn first_job_wires_the_queue_and_later_jobs_extend_the_registry() {
    let sandbox = Sandbox::new();
    let root = sandbox.new_app("shop", &[]);
    let (report, ok) = sandbox.json(&["g", "job", "SendWelcomeJob", "user_id:integer", "note:text?"], &root);
    assert!(ok, "{report}");
    assert_eq!(report["created"], json!(["src/jobs/send_welcome.rs", "src/jobs/mod.rs"]));
    assert_eq!(report["updated"], json!(["src/lib.rs", "wrangler.toml"]));
    assert_eq!(
        report["next"],
        json!([
            "enqueue it from a handler: ocre::jobs::enqueue(&ctx, &jobs::Job::SendWelcome(jobs::SendWelcome { user_id, note })).await?",
            "ocre dev (jobs run locally; look for `[ocre jobs]` lines in the output)",
            "ocre deploy creates the queue shop-jobs and its dead-letter queue",
        ])
    );
    let job = read(&root, "src/jobs/send_welcome.rs");
    assert!(
        job.starts_with("//! Send welcome job. Generated by `ocre g job SendWelcomeJob user_id:integer note:text?`.")
    );
    assert!(
        job.contains(
            "pub struct SendWelcome {\n    pub user_id: i64,\n    pub note: Option<String>,\n}\n\nimpl SendWelcome {"
        ),
        "{job}"
    );
    assert!(job.contains("pub async fn perform(self, _ctx: &Ctx) -> Result<()> {\n        Ok(())\n    }"), "{job}");
    let registry = read(&root, "src/jobs/mod.rs");
    assert!(
        registry.contains("// ocre:jobs\npub mod send_welcome;\npub use send_welcome::SendWelcome;\n"),
        "{registry}"
    );
    assert!(registry.contains("    // ocre:job-variants\n    SendWelcome(SendWelcome),\n}"), "{registry}");
    assert!(
        registry.contains("        // ocre:job-dispatch\n        Job::SendWelcome(job) => job.perform(&ctx).await,\n"),
        "{registry}"
    );
    let lib = read(&root, "src/lib.rs");
    assert!(lib.contains("// ocre:modules\nmod jobs;\n"), "{lib}");
    assert!(
        lib.ends_with(
            "#[worker::event(queue)]\nasync fn queue(batch: worker::MessageBatch<String>, env: worker::Env, _ctx: \
             worker::Context) -> worker::Result<()> {\n    ocre::jobs::consume(batch, env, jobs::perform).await\n}\n"
        ),
        "{lib}"
    );
    let wrangler: toml::Table = read(&root, "wrangler.toml").parse().unwrap();
    assert_eq!(wrangler["queues"]["producers"][0]["binding"].as_str(), Some("JOBS"));
    assert_eq!(wrangler["queues"]["producers"][0]["queue"].as_str(), Some("shop-jobs"));
    let consumer = &wrangler["queues"]["consumers"][0];
    assert_eq!(consumer["queue"].as_str(), Some("shop-jobs"));
    assert_eq!(consumer["dead_letter_queue"].as_str(), Some("shop-jobs-failed"));
    assert_eq!(consumer["max_retries"].as_integer(), Some(5));

    // A second job, without arguments: only the registry changes.
    let output = sandbox.ocre(&["g", "job", "cleanup"], &root);
    assert!(output.status.success());
    let (stdout, _) = text(&output);
    assert!(stdout.starts_with("  create  src/jobs/cleanup.rs\n  update  src/jobs/mod.rs\n"), "{stdout}");
    assert!(stdout.contains("jobs::Job::Cleanup(jobs::Cleanup {})"), "{stdout}");
    assert!(!stdout.contains("ocre deploy creates"), "{stdout}");
    assert!(read(&root, "src/jobs/cleanup.rs").contains("pub struct Cleanup {}\n\nimpl Cleanup {"));
    let registry = read(&root, "src/jobs/mod.rs");
    assert!(registry.contains("    Cleanup(Cleanup),\n    SendWelcome(SendWelcome),\n"), "{registry}");
    assert_eq!(read(&root, "src/lib.rs").matches("event(queue)").count(), 1);
    assert_eq!(read(&root, "wrangler.toml").matches("[[queues.producers]]").count(), 1);
}

#[test]
fn a_hand_written_jobs_producer_is_reused() {
    let sandbox = Sandbox::new();
    let root = sandbox.new_app("shop", &[]);
    let wrangler = read(&root, "wrangler.toml") + "\n[[queues.producers]]\nbinding = \"JOBS\"\nqueue = \"tasks\"\n";
    fs::write(root.join("wrangler.toml"), &wrangler).unwrap();
    let (report, ok) = sandbox.json(&["g", "job", "Ping"], &root);
    assert!(ok, "{report}");
    assert_eq!(report["updated"], json!(["src/lib.rs"]));
    assert_eq!(report["next"][2], "ocre deploy creates the queue tasks and its dead-letter queue");
    assert_eq!(read(&root, "wrangler.toml"), wrangler);
}

#[test]
fn job_errors_name_the_fix_and_write_nothing() {
    let sandbox = Sandbox::new();
    let root = sandbox.new_app("shop", &[]);
    let pristine = |root: &std::path::Path| !root.join("src/jobs").exists();
    let cases: &[(&[&str], &str)] = &[
        (&["g", "job", "2Fast"], "invalid job name `2Fast`"),
        (&["g", "job", "Type"], "invalid job name `Type`"),
        (&["g", "job", "Job"], "invalid job name `Job`"),
        (&["g", "job", "Import", "path"], "field `path` has no type"),
        (&["g", "job", "Import", "path:string^"], "job field `path` cannot be unique"),
        (&["g", "job", "Import", "csv:attachment"], "job field `csv` cannot be an attachment"),
    ];
    for (args, error) in cases {
        let (report, ok) = sandbox.json(args, &root);
        assert!(!ok);
        assert_eq!(report["error"], *error, "{args:?}");
        assert!(report["hint"].is_string(), "{report}");
    }
    assert!(pristine(&root));

    // A queue handler written by hand is not duplicated.
    let lib = read(&root, "src/lib.rs");
    fs::write(root.join("src/lib.rs"), format!("{lib}\n// #[worker::event(queue)]\n")).unwrap();
    let (report, _) = sandbox.json(&["g", "job", "Ping"], &root);
    assert_eq!(report["error"], "src/lib.rs already handles the `queue` event");
    fs::write(root.join("src/lib.rs"), "fn main() {}\n").unwrap();
    let (report, _) = sandbox.json(&["g", "job", "Ping"], &root);
    assert_eq!(report["error"], "src/lib.rs is missing the `// ocre:modules` marker");
    fs::write(root.join("src/lib.rs"), &lib).unwrap();

    // wrangler.toml problems.
    let wrangler = read(&root, "wrangler.toml");
    fs::write(root.join("wrangler.toml"), wrangler.replacen("name = \"shop\"\n", "", 1)).unwrap();
    let (report, _) = sandbox.json(&["g", "job", "Ping"], &root);
    // Without `name`, Project::find still works (it reads the D1 binding).
    assert_eq!(report["error"], "wrangler.toml has no `name`");
    fs::write(root.join("wrangler.toml"), wrangler.clone() + "\n[[queues.producers]]\nbinding = \"JOBS\"\n").unwrap();
    let (report, _) = sandbox.json(&["g", "job", "Ping"], &root);
    assert_eq!(report["error"], "the JOBS queue producer in wrangler.toml has no `queue`");
    fs::write(root.join("wrangler.toml"), &wrangler).unwrap();
    assert!(pristine(&root));
    assert_eq!(read(&root, "src/lib.rs"), lib);

    // A registry without its markers.
    let (report, ok) = sandbox.json(&["g", "job", "Ping"], &root);
    assert!(ok, "{report}");
    let registry = read(&root, "src/jobs/mod.rs");
    for marker in ["// ocre:jobs", "// ocre:job-variants", "// ocre:job-dispatch"] {
        fs::write(root.join("src/jobs/mod.rs"), registry.replace(marker, "")).unwrap();
        let (report, _) = sandbox.json(&["g", "job", "Pong"], &root);
        assert_eq!(report["error"], format!("src/jobs/mod.rs is missing the `{marker}` marker"));
        assert!(!root.join("src/jobs/pong.rs").exists());
    }
    fs::write(root.join("src/jobs/mod.rs"), &registry).unwrap();
    let (report, _) = sandbox.json(&["g", "job", "Ping"], &root);
    assert_eq!(report["error"], "src/jobs/ping.rs already exists");
}

#[test]
fn schedules_add_crons_and_dispatch_by_expression() {
    let sandbox = Sandbox::new();
    let root = sandbox.new_app("shop", &[]);
    let (report, ok) = sandbox.json(&["g", "schedule", "NightlyCleanup", " 0  3 * * * "], &root);
    assert!(ok, "{report}");
    assert_eq!(report["created"], json!(["src/schedules/nightly_cleanup.rs", "src/schedules/mod.rs"]));
    assert_eq!(report["updated"], json!(["wrangler.toml", "src/lib.rs"]));
    assert_eq!(
        report["next"][0],
        "ocre dev, then: curl 'http://localhost:8787/cdn-cgi/local/scheduled?cron=0+3+*+*+*'"
    );
    let task = read(&root, "src/schedules/nightly_cleanup.rs");
    assert!(task.starts_with(
        "//! Nightly cleanup: scheduled task. Generated by `ocre g schedule NightlyCleanup \"0 3 * * *\"`."
    ));
    assert!(task.contains("pub async fn run(_ctx: &Ctx) -> Result<()> {\n    Ok(())\n}"), "{task}");
    let registry = read(&root, "src/schedules/mod.rs");
    assert!(registry.contains("// ocre:schedules\npub mod nightly_cleanup;\n"), "{registry}");
    assert!(
        registry.contains("// ocre:schedule-dispatch\n        \"0 3 * * *\" => nightly_cleanup::run(&ctx).await,\n")
    );
    let lib = read(&root, "src/lib.rs");
    assert!(lib.contains("// ocre:modules\nmod schedules;\n"), "{lib}");
    assert!(
        lib.ends_with(
            "#[worker::event(scheduled)]\nasync fn scheduled(event: worker::ScheduledEvent, env: worker::Env, _ctx: \
             worker::ScheduleContext) {\n    ocre::jobs::cron(event, env, schedules::run).await\n}\n"
        ),
        "{lib}"
    );
    assert!(read(&root, "wrangler.toml").ends_with("[triggers]\ncrons = [\"0 3 * * *\"]\n"));

    // Weekday with `#` is escaped in the local URL; the array grows in place.
    let (report, ok) = sandbox.json(&["g", "schedule", "monthly_report", "0 9 * * MON#1"], &root);
    assert!(ok, "{report}");
    assert_eq!(report["updated"], json!(["wrangler.toml", "src/schedules/mod.rs"]));
    assert!(report["next"][0].as_str().unwrap().ends_with("?cron=0+9+*+*+MON%231'"), "{report}");
    assert!(read(&root, "wrangler.toml").ends_with("[triggers]\ncrons = [\"0 3 * * *\", \"0 9 * * MON#1\"]\n"));
    assert_eq!(read(&root, "src/lib.rs").matches("event(scheduled)").count(), 1);

    // Duplicates and bad input.
    let cases: &[(&[&str], &str)] = &[
        (&["g", "schedule", "again", "0 3 * * *"], "cron `0 3 * * *` is already in [triggers] crons"),
        (&["g", "schedule", "hourly", "0 * * *"], "invalid cron expression `0 * * *`"),
        (&["g", "schedule", "hourly", "0 * * * ?"], "invalid cron expression `0 * * * ?`"),
        (&["g", "schedule", "9lives", "0 * * * *"], "invalid schedule name `9lives`"),
        (&["g", "schedule", "match", "0 * * * *"], "invalid schedule name `match`"),
        (&["g", "schedule", "nightly_cleanup", "5 * * * *"], "src/schedules/nightly_cleanup.rs already exists"),
    ];
    for (args, error) in cases {
        let (report, ok) = sandbox.json(args, &root);
        assert!(!ok);
        assert_eq!(report["error"], *error, "{args:?}");
        assert!(report["hint"].is_string(), "{report}");
    }
    assert!(!root.join("src/schedules/again.rs").exists() && !root.join("src/schedules/hourly.rs").exists());
}

#[test]
fn crons_are_edited_where_they_are() {
    let sandbox = Sandbox::new();
    let root = sandbox.new_app("shop", &[]);
    let wrangler = read(&root, "wrangler.toml");
    let with = |extra: &str| fs::write(root.join("wrangler.toml"), format!("{wrangler}{extra}")).unwrap();
    let crons = |root: &std::path::Path| {
        let config: toml::Table = read(root, "wrangler.toml").parse().unwrap();
        config["triggers"]["crons"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| c.as_str().unwrap().to_owned())
            .collect::<Vec<_>>()
    };

    // A multi-line array followed by another table.
    with("\n[triggers]\n# kept\ncrons = [\n  \"0 1 * * *\",\n  \"0 2 * * *\",\n]\n\n[observability]\nenabled = true\n");
    let (report, ok) = sandbox.json(&["g", "schedule", "a", "0 3 * * *"], &root);
    assert!(ok, "{report}");
    let text = read(&root, "wrangler.toml");
    assert!(
        text.ends_with("[triggers]\n# kept\ncrons = [\"0 1 * * *\", \"0 2 * * *\", \"0 3 * * *\"]\n\n[observability]\nenabled = true\n"),
        "{text}"
    );

    // `[triggers]` without `crons`, and more crons than the free plan allows.
    fs::remove_dir_all(root.join("src/schedules")).unwrap();
    fs::write(root.join("src/lib.rs"), read(&root, "src/lib.rs").replace("event(scheduled)", "")).unwrap();
    with("\n[triggers]\n\n[vars.more]\nX = \"1\"\n");
    for (i, name) in ["a", "b", "c", "d", "e"].iter().enumerate() {
        let (report, ok) = sandbox.json(&["g", "schedule", name, &format!("{i} * * * *")], &root);
        assert!(ok, "{report}");
        assert_eq!(report["next"].as_array().unwrap().len(), 2, "{report}");
    }
    let (report, _) = sandbox.json(&["g", "schedule", "f", "9 * * * *"], &root);
    assert_eq!(
        report["next"][2],
        "this app now has 6 crons; the free plan allows 5 per account: run several tasks from one cron"
    );
    assert_eq!(crons(&root).len(), 6);
    assert!(read(&root, "wrangler.toml").contains("[vars.more]\nX = \"1\"\n"));

    // Forms Ocre does not edit.
    fs::remove_dir_all(root.join("src/schedules")).unwrap();
    let lib = read(&root, "src/lib.rs").replace("event(scheduled)", "");
    fs::write(root.join("src/lib.rs"), &lib).unwrap();
    for extra in ["\n[triggers.crons]\nx = 1\n", "\n[triggers]\ncrons = [1]\n"] {
        with(extra);
        let (report, _) = sandbox.json(&["g", "schedule", "a", "0 3 * * *"], &root);
        assert_eq!(report["error"], "wrangler.toml defines `triggers` in a form Ocre cannot edit", "{extra}");
    }
    fs::write(root.join("wrangler.toml"), format!("triggers = {{ crons = [] }}\n{wrangler}")).unwrap();
    let (report, _) = sandbox.json(&["g", "schedule", "a", "0 3 * * *"], &root);
    assert_eq!(report["error"], "wrangler.toml defines `triggers` in a form Ocre cannot edit");
    fs::write(root.join("wrangler.toml"), format!("{wrangler}\n[triggers\n")).unwrap();
    let (report, _) = sandbox.json(&["g", "schedule", "a", "0 3 * * *"], &root);
    assert!(report["error"].as_str().unwrap().starts_with("wrangler.toml is not valid TOML"), "{report}");
    assert!(!root.join("src/schedules").exists());

    // lib.rs problems.
    with("");
    fs::write(root.join("src/lib.rs"), format!("{lib}\n// #[worker::event(scheduled)]\n")).unwrap();
    let (report, _) = sandbox.json(&["g", "schedule", "a", "0 3 * * *"], &root);
    assert_eq!(report["error"], "src/lib.rs already handles the `scheduled` event");
    fs::write(root.join("src/lib.rs"), "fn main() {}\n").unwrap();
    let (report, _) = sandbox.json(&["g", "schedule", "a", "0 3 * * *"], &root);
    assert_eq!(report["error"], "src/lib.rs is missing the `// ocre:modules` marker");
    fs::write(root.join("src/lib.rs"), &lib).unwrap();

    // A registry without its markers.
    let (report, ok) = sandbox.json(&["g", "schedule", "a", "0 3 * * *"], &root);
    assert!(ok, "{report}");
    let registry = read(&root, "src/schedules/mod.rs");
    for marker in ["// ocre:schedules", "// ocre:schedule-dispatch"] {
        fs::write(root.join("src/schedules/mod.rs"), registry.replace(marker, "")).unwrap();
        let (report, _) = sandbox.json(&["g", "schedule", "b", "0 4 * * *"], &root);
        assert_eq!(report["error"], format!("src/schedules/mod.rs is missing the `{marker}` marker"));
    }
    assert_eq!(crons(&root), ["0 3 * * *"]);
}

#[test]
fn deploy_creates_missing_queues_once() {
    let sandbox = Sandbox::new();
    let root = sandbox.new_app("shop", &[]);
    sandbox.set("has_secret");
    let (report, ok) = sandbox.json(&["g", "job", "Ping"], &root);
    assert!(ok, "{report}");
    sandbox.set("queue_shop-jobs");

    let output = sandbox.ocre(&["deploy"], &root);
    let (stdout, _) = text(&output);
    assert!(output.status.success(), "{stdout}");
    assert!(stdout.contains("Created queue shop-jobs-failed on Cloudflare\n"), "{stdout}");
    let calls = sandbox.calls();
    assert_eq!(
        calls[..4],
        [
            "queues info shop-jobs",
            "queues info shop-jobs-failed",
            "queues create shop-jobs-failed",
            "secret list --format json"
        ]
    );

    // Everything exists now: nothing to create.
    let (report, ok) = sandbox.json(&["deploy"], &root);
    assert!(ok, "{report}");
    assert!(report.get("provisioned").is_none(), "{report}");

    fs::remove_file(sandbox.work.join("../state/queue_shop-jobs")).unwrap();
    let (report, ok) = sandbox.json(&["deploy"], &root);
    assert!(ok, "{report}");
    assert_eq!(report["provisioned"], json!(["queue shop-jobs"]));

    // Any other failure stops the deploy before it starts.
    sandbox.set("queues_info_fails");
    let (report, ok) = sandbox.json(&["deploy"], &root);
    assert!(!ok);
    assert_eq!(report["error"], "`wrangler queues info shop-jobs` failed: ✘ [ERROR] queues_info_fails");
    assert!(report["hint"].as_str().unwrap().contains("ocre login"), "{report}");
    fs::remove_file(sandbox.work.join("../state/queues_info_fails")).unwrap();
    fs::remove_file(sandbox.work.join("../state/queue_shop-jobs")).unwrap();
    sandbox.set("queues_create_fails");
    let (report, ok) = sandbox.json(&["deploy"], &root);
    assert!(!ok);
    assert_eq!(report["error"], "`wrangler queues create shop-jobs` failed (exit status: 1)");
    assert_eq!(sandbox.calls().last().unwrap(), "queues create shop-jobs", "never deployed without its queues");
}
