//! Random tokens for emailed links and API keys, stored as digests.
//!
//! Used by `ocre g auth` for password-reset and magic-link emails and for API
//! keys. A token is 32 random bytes (256 bits) from the platform's secure
//! random generator (WebCrypto on Workers), encoded as URL-safe base64
//! without padding: 43 characters, safe in URLs, headers and emails.
//!
//! Store only [`digest`]s: a leaked database then holds no usable token. A
//! fast hash (SHA-256) is enough here because tokens are random and long;
//! passwords, which people choose, need [`crate::password`] instead. Compare
//! secrets that cannot be looked up by digest with [`constant_time_eq`].
//!
//! Cost: one SHA-256 per [`digest`]; this module uses no binding (the app
//! stores the digest in D1).
//!
//! ```
//! // Issue: email or show `token` once, store `stored` (e.g. in a `token_digest` column).
//! let token = ocre::token::generate();
//! let stored = ocre::token::digest(&token);
//! // Later, from a request: look the row up by digest (`WHERE token_digest = ?1`).
//! assert_eq!(ocre::token::digest(&token), stored);
//! ```

use std::fmt::Write as _;

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use sha2::{Digest as _, Sha256};

/// Random bytes in a token generated by [`generate`]: 32 (256 bits).
///
/// # Examples
///
/// ```
/// assert_eq!(ocre::token::TOKEN_BYTES, 32);
/// ```
pub const TOKEN_BYTES: usize = 32;

/// A new random token: [`TOKEN_BYTES`] secure random bytes as URL-safe base64 without padding (43 characters).
///
/// Show or email it once and store only its [`digest`].
///
/// # Panics
///
/// If the platform's secure random generator is unavailable (WebCrypto on
/// Workers, the OS generator natively), which does not happen on supported
/// targets.
///
/// # Examples
///
/// ```
/// let token = ocre::token::generate();
/// assert_eq!(token.len(), 43);
/// assert!(token.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'));
/// assert_ne!(token, ocre::token::generate());
/// ```
pub fn generate() -> String {
    URL_SAFE_NO_PAD.encode(random_bytes::<TOKEN_BYTES>())
}

/// A random id for URLs: 22 URL-safe characters (128 bits), the value of a
/// `public_id:token` column. Unguessable, so a page at `/videos/<public_id>`
/// cannot be found by counting, and it says nothing about how many rows exist.
///
/// # Panics
///
/// As [`generate`].
///
/// # Examples
///
/// ```
/// let id = ocre::token::public_id();
/// assert_eq!(id.len(), 22);
/// assert!(id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_'));
/// ```
pub fn public_id() -> String {
    URL_SAFE_NO_PAD.encode(random_bytes::<16>())
}

/// SHA-256 of `token` as 64 lowercase hex characters: the value to store and look up.
///
/// Query by it (`WHERE digest = ?1`), so the database never holds the token
/// itself. Deterministic: the same token always gives the same digest.
///
/// # Examples
///
/// ```
/// assert_eq!(ocre::token::digest("abc"), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
/// ```
pub fn digest(token: &str) -> String {
    let hash = Sha256::digest(token.as_bytes());
    let mut hex = String::with_capacity(hash.len() * 2);
    for byte in hash {
        write!(hex, "{byte:02x}").expect("writing to a String");
    }
    hex
}

/// Whether `a` equals `b`, compared in constant time for equal lengths.
///
/// Response timing then does not reveal how many leading bytes matched.
/// Different lengths return `false` at once: lengths are not secret.
///
/// # Examples
///
/// ```
/// assert!(ocre::token::constant_time_eq(b"secret", b"secret"));
/// assert!(!ocre::token::constant_time_eq(b"secret", b"secreT"));
/// assert!(!ocre::token::constant_time_eq(b"secret", b"secrets"));
/// ```
pub fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let difference = a.iter().zip(b).fold(0u8, |acc, (x, y)| acc | (x ^ y));
    // Keeps the optimizer from turning the loop into an early exit.
    std::hint::black_box(difference) == 0
}

/// `N` bytes from the secure random generator.
pub(crate) fn random_bytes<const N: usize>() -> [u8; N] {
    let mut bytes = [0u8; N];
    getrandom::getrandom(&mut bytes).expect("the secure random generator is available");
    bytes
}

#[cfg(test)]
#[path = "../tests/token.rs"]
mod tests;
