name = "ocre-blog"
main = "build/index.js"
compatibility_date = "2026-09-01"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "ocre-blog"
migrations_dir = "migrations"
