//! `ocre generate mailer`: `src/mailers/<name>.rs`, one function per action
//! building an `ocre::mail::Email`, with askama text and HTML templates in
//! full-stack apps.

use std::fmt::Write as _;

use super::{Edits, MODULES_MARKER, fields::RESERVED, insert_after_marker};
use crate::{
    CliResult,
    names::{humanize, is_identifier, split_words},
    output::CliError,
    project::Project,
};

pub(super) const MAILERS_MARKER: &str = "// ocre:mailers";

pub fn mailer(project: &Project, name: &str, actions: &[String]) -> CliResult {
    let module = module_name(name)?;
    let actions = action_names(actions)?;
    let command = format!("ocre g mailer {name} {}", actions.join(" "));
    let mut edits = Edits::new(project);
    let path = format!("src/mailers/{module}.rs");
    if project.api_only {
        edits.create(&path, api_mailer_rs(&module, &actions, &command))?;
    } else {
        edits.create(&path, mailer_rs(&module, &actions, &command))?;
        for action in &actions {
            edits.create(&format!("templates/mailers/{module}/{action}.txt"), text_template(&module, action))?;
            edits.create(&format!("templates/mailers/{module}/{action}.html"), html_template(&module, action))?;
        }
    }
    register(&mut edits, &module)?;
    let mut report = edits.apply("generate mailer")?;
    report.next = vec![
        format!("send it from a handler: ocre::mail::send(&ctx, mailers::{module}::{}(&address)?).await?", actions[0]),
        "ocre dev (MAIL_ADAPTER=log in .dev.vars prints each email instead of sending it)".to_owned(),
    ];
    Ok(report)
}

/// `UserMailer`, `user_mailer` or `User` -> `user`.
fn module_name(name: &str) -> Result<String, CliError> {
    let mut words = split_words(name);
    if words.len() > 1 && words.last().is_some_and(|w| w == "mailer") {
        words.pop();
    }
    let module = words.join("_");
    if !is_identifier(&module) || RESERVED.contains(&module.as_str()) {
        return Err(CliError::new(format!("invalid mailer name `{name}`"))
            .hint("use a name starting with a letter that is not a Rust keyword, e.g. `User` or `Billing`"));
    }
    Ok(module)
}

/// Action names as snake_case function names, each once.
fn action_names(actions: &[String]) -> Result<Vec<String>, CliError> {
    let mut names: Vec<String> = Vec::with_capacity(actions.len());
    for action in actions {
        let name = split_words(action).join("_");
        if !is_identifier(&name) || RESERVED.contains(&name.as_str()) {
            return Err(CliError::new(format!("invalid action name `{action}`")).hint(
                "use snake_case starting with a letter, not a Rust or SQL keyword, e.g. `welcome` or `password_reset`",
            ));
        }
        if names.contains(&name) {
            return Err(CliError::new(format!("action `{name}` is listed twice")).hint("list each action once"));
        }
        names.push(name);
    }
    Ok(names)
}

/// `password_reset` -> `PasswordReset`.
pub(super) fn pascal(snake: &str) -> String {
    snake
        .split('_')
        .map(|word| {
            let mut chars = word.chars();
            chars.next().map_or_else(String::new, |first| first.to_ascii_uppercase().to_string() + chars.as_str())
        })
        .collect()
}

fn header(module: &str, command: &str, api_only: bool) -> String {
    let source = if api_only {
        "Each function builds an `Email` (text only; add `.html(...)` for HTML)".to_owned()
    } else {
        format!("Each function builds an `Email` from templates/mailers/{module}/<action>.txt and .html")
    };
    format!(
        "//! {} emails. Generated by `{command}`.\n//!\n//! {source}.\n//! Send one from a handler (`MAIL_ADAPTER` picks log, Resend or Cloudflare):\n//! `ocre::mail::send(&ctx, crate::mailers::{module}::<action>(&address)?).await?`\n\n",
        humanize(module),
    )
}

fn mailer_rs(module: &str, actions: &[String], command: &str) -> String {
    let mut out = header(module, command, false);
    out.push_str("use askama::Template;\nuse ocre::{Result, mail::Email};\n");
    for action in actions {
        let (pascal, subject) = (pascal(action), humanize(action));
        for (kind, extension) in [("Text", "txt"), ("Html", "html")] {
            write!(
                out,
                "\n#[derive(Template)]\n#[template(path = \"mailers/{module}/{action}.{extension}\")]\nstruct {pascal}{kind}<'a> {{\n    to: &'a str,\n}}\n"
            )
            .expect("writing to a String");
        }
        write!(
            out,
            "\n/// \"{subject}\" email to `to`.\npub fn {action}(to: &str) -> Result<Email> {{\n    let text = {pascal}Text {{ to }}.render()?;\n    let html = {pascal}Html {{ to }}.render()?;\n    Ok(Email::new(to, \"{subject}\", text).html(html))\n}}\n"
        )
        .expect("writing to a String");
    }
    out
}

fn api_mailer_rs(module: &str, actions: &[String], command: &str) -> String {
    let mut out = header(module, command, true);
    out.push_str("use ocre::{Result, mail::Email};\n");
    for action in actions {
        let subject = humanize(action);
        write!(
            out,
            "\n/// \"{subject}\" email to `to`.\npub fn {action}(to: &str) -> Result<Email> {{\n    let text = format!(\"Hello {{to}},\\n\\nThis is the {} email. Edit it in src/mailers/{module}.rs.\\n\");\n    Ok(Email::new(to, \"{subject}\", text))\n}}\n",
            subject.to_lowercase(),
        )
        .expect("writing to a String");
    }
    out
}

fn text_template(module: &str, action: &str) -> String {
    format!(
        "Hello {{{{ to }}}},\n\nThis is the {} email. Edit templates/mailers/{module}/{action}.txt.\n",
        humanize(action).to_lowercase()
    )
}

fn html_template(module: &str, action: &str) -> String {
    format!(
        "<!DOCTYPE html>\n<html>\n<body>\n<p>Hello {{{{ to }}}},</p>\n<p>This is the {} email. Edit templates/mailers/{module}/{action}.html.</p>\n</body>\n</html>\n",
        humanize(action).to_lowercase()
    )
}

/// Adds `pub mod <module>;` to src/mailers/mod.rs, creating it (and
/// `mod mailers;` in src/lib.rs) on first use.
fn register(edits: &mut Edits, module: &str) -> Result<(), CliError> {
    let registry = match edits.read("src/mailers/mod.rs")? {
        Some(source) => source,
        None => {
            let lib = edits.read("src/lib.rs")?.unwrap_or_default();
            let lib = insert_after_marker(&lib, MODULES_MARKER, "mod mailers;").ok_or_else(|| {
                CliError::new("src/lib.rs is missing the `// ocre:modules` marker")
                    .hint("put `// ocre:modules` on its own line where `mod` declarations go")
            })?;
            edits.update("src/lib.rs", lib);
            format!(
                "//! Mailers: functions that build emails. `ocre g mailer` adds them below.\n\n// A mailer is often generated before a handler sends it.\n#![allow(dead_code)]\n\n{MAILERS_MARKER}\n"
            )
        }
    };
    let registry = insert_after_marker(&registry, MAILERS_MARKER, &format!("pub mod {module};"))
        .ok_or_else(|| CliError::new(format!("src/mailers/mod.rs is missing the `{MAILERS_MARKER}` marker")))?;
    edits.update("src/mailers/mod.rs", registry);
    Ok(())
}
