//! `ocre generate scaffold`: model + HTML pages (askama) for full CRUD.

use std::fmt::Write as _;

use super::{
    Edits,
    fields::{Field, FieldType, parse_fields},
    model::ensure_model,
    register_routes,
};
use crate::{CliResult, names::ModelNames, project::Project};

pub fn scaffold(project: &Project, name: &str, specs: &[String]) -> CliResult {
    let names = ModelNames::parse(name)?;
    let fields = parse_fields(specs)?;
    let command = format!("ocre g scaffold {name} {}", specs.join(" "));
    let mut edits = Edits::new(project);
    ensure_model(&mut edits, &names, &fields, &command)?;
    let plural = &names.plural;
    edits.create(&format!("src/{plural}.rs"), controller_rs(&names, &fields, &command))?;
    for (file, contents) in [
        ("index.html", index_html(&names, &fields)),
        ("show.html", show_html(&names, &fields)),
        ("new.html", page_html(&names, false)),
        ("edit.html", page_html(&names, true)),
        ("_form.html", form_fields_html(&fields)),
    ] {
        edits.create(&format!("templates/{plural}/{file}"), contents)?;
    }
    register_routes(&mut edits, plural)?;
    let mut report = edits.apply("generate scaffold")?;
    report.next =
        vec!["ocre migrate".to_owned(), "ocre dev".to_owned(), format!("open http://localhost:8787/{plural}")];
    Ok(report)
}

/// `PostForm` field type: text for anything typed in an input, `bool` for checkboxes.
fn form_type(field: &Field) -> &'static str {
    if field.ty == FieldType::Boolean { "bool" } else { "String" }
}

/// Expression turning form text into the model value (`v` is a Validator).
fn from_form(field: &Field) -> String {
    let name = &field.name;
    match (field.ty, field.optional) {
        (FieldType::Boolean, _) => format!("self.{name}"),
        (ty, false) if ty.is_numeric() => format!("v.number(\"{name}\", &self.{name}).unwrap_or_default()"),
        (ty, true) if ty.is_numeric() => format!("v.optional_number(\"{name}\", &self.{name})"),
        (_, false) => format!("self.{name}.clone()"),
        (_, true) => format!("(!self.{name}.trim().is_empty()).then(|| self.{name}.clone())"),
    }
}

/// Expression turning the model value into form text.
fn to_form(field: &Field, record: &str) -> String {
    let name = &field.name;
    match (field.ty, field.optional) {
        (FieldType::Boolean, _) => format!("{record}.{name}"),
        (ty, false) if ty.is_numeric() => format!("{record}.{name}.to_string()"),
        (ty, true) if ty.is_numeric() => format!("{record}.{name}.map(|value| value.to_string()).unwrap_or_default()"),
        (_, false) => format!("{record}.{name}.clone()"),
        (_, true) => format!("{record}.{name}.clone().unwrap_or_default()"),
    }
}

fn controller_rs(names: &ModelNames, fields: &[Field], command: &str) -> String {
    let ModelNames { model, singular, plural, human_singular, human_plural } = names;
    let mut form_fields = String::new();
    let mut new_values = String::new();
    let mut change_values = String::new();
    let mut record_values = String::new();
    for field in fields {
        let name = &field.name;
        if field.ty == FieldType::Boolean {
            form_fields.push_str("    /// Unchecked checkboxes are not submitted.\n");
        }
        writeln!(form_fields, "    pub {name}: {},", form_type(field)).expect("writing to a String");
        let value = from_form(field);
        writeln!(new_values, "            {name}: {value},").expect("writing to a String");
        writeln!(change_values, "            {name}: Some({value}),").expect("writing to a String");
        writeln!(record_values, "            {name}: {},", to_form(field, "record")).expect("writing to a String");
    }

    format!(
        r#"//! {human_plural} pages (HTML). Generated by `{command}`.
//! Queries and rules live in the model, `crate::models::{singular}`.

use askama::Template;
use axum::{{
    Form, Router,
    extract::{{Path, State}},
    http::StatusCode,
    response::{{Html, IntoResponse, Redirect, Response}},
    routing::{{get, post}},
}};
use ocre::{{Ctx, Error, FieldError, Flash, OptionExt, Page, Result, Session, Validator, render}};
use serde::Deserialize;

use crate::models::{singular}::{{self, New{model}, {model}, {model}Changes}};

pub fn routes() -> Router<Ctx> {{
    Router::new()
        .route("/{plural}", get(index).post(create))
        .route("/{plural}/new", get(new))
        .route("/{plural}/{{id}}", get(show).post(update))
        .route("/{plural}/{{id}}/edit", get(edit))
        .route("/{plural}/{{id}}/delete", post(delete))
}}

/// What the new and edit forms submit, as typed: numbers stay text until
/// validated, so a typo shows a field error instead of a failed request.
/// A missing field is empty (and unchecked for checkboxes).
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default)]
pub struct {model}Form {{
{form_fields}}}

impl {model}Form {{
    fn from_record(record: &{model}) -> Self {{
        Self {{
{record_values}        }}
    }}

    /// Parses the text and runs the model's checks, so the form shows every
    /// error at once (database checks run in `create`).
    fn to_new(&self) -> Result<New{model}> {{
        let mut v = Validator::new();
        let new = New{model} {{
{new_values}        }};
        v.merge(new.validate()).finish()?;
        Ok(new)
    }}

    fn to_changes(&self) -> Result<{model}Changes> {{
        let mut v = Validator::new();
        let changes = {model}Changes {{
{change_values}        }};
        v.merge(changes.validate()).finish()?;
        Ok(changes)
    }}
}}

#[derive(Template)]
#[template(path = "{plural}/index.html")]
struct IndexView {{
    flash: Flash,
    {plural}: Vec<{model}>,
}}

#[derive(Template)]
#[template(path = "{plural}/show.html")]
struct ShowView {{
    flash: Flash,
    {singular}: {model},
}}

#[derive(Template)]
#[template(path = "{plural}/new.html")]
struct NewView {{
    form: {model}Form,
    errors: Vec<FieldError>,
}}

#[derive(Template)]
#[template(path = "{plural}/edit.html")]
struct EditView {{
    id: i64,
    form: {model}Form,
    errors: Vec<FieldError>,
}}

async fn index(State(ctx): State<Ctx>, flash: Flash, page: Page) -> Result<Html<String>> {{
    render(&IndexView {{ flash, {plural}: {singular}::all(&ctx, page).await? }})
}}

async fn show(State(ctx): State<Ctx>, flash: Flash, Path(id): Path<i64>) -> Result<Html<String>> {{
    render(&ShowView {{ flash, {singular}: {singular}::find(&ctx, id).await?.or_404()? }})
}}

async fn new() -> Result<Html<String>> {{
    render(&NewView {{ form: {model}Form::default(), errors: vec![] }})
}}

async fn create(State(ctx): State<Ctx>, session: Session, Form(form): Form<{model}Form>) -> Result<Response> {{
    let created = match form.to_new() {{
        Ok(new) => {singular}::create(&ctx, new).await,
        Err(err) => Err(err),
    }};
    match created {{
        Ok(record) => {{
            session.flash("notice", "{human_singular} was successfully created.")?;
            Ok(Redirect::to(&format!("/{plural}/{{}}", record.id)).into_response())
        }}
        Err(Error::Invalid(errors)) => {{
            Ok((StatusCode::UNPROCESSABLE_ENTITY, render(&NewView {{ form, errors }})?).into_response())
        }}
        Err(err) => Err(err),
    }}
}}

async fn edit(State(ctx): State<Ctx>, Path(id): Path<i64>) -> Result<Html<String>> {{
    let record = {singular}::find(&ctx, id).await?.or_404()?;
    render(&EditView {{ id, form: {model}Form::from_record(&record), errors: vec![] }})
}}

async fn update(
    State(ctx): State<Ctx>,
    session: Session,
    Path(id): Path<i64>,
    Form(form): Form<{model}Form>,
) -> Result<Response> {{
    let updated = match form.to_changes() {{
        Ok(changes) => {singular}::update(&ctx, id, changes).await,
        Err(err) => Err(err),
    }};
    match updated {{
        Ok(record) => {{
            let record = record.or_404()?;
            session.flash("notice", "{human_singular} was successfully updated.")?;
            Ok(Redirect::to(&format!("/{plural}/{{}}", record.id)).into_response())
        }}
        Err(Error::Invalid(errors)) => {{
            Ok((StatusCode::UNPROCESSABLE_ENTITY, render(&EditView {{ id, form, errors }})?).into_response())
        }}
        Err(err) => Err(err),
    }}
}}

async fn delete(State(ctx): State<Ctx>, session: Session, Path(id): Path<i64>) -> Result<Redirect> {{
    if !{singular}::delete(&ctx, id).await? {{
        return Err(Error::NotFound);
    }}
    session.flash("notice", "{human_singular} was successfully destroyed.")?;
    Ok(Redirect::to("/{plural}"))
}}
"#
    )
}

/// Flash messages set by the previous request (create, update, delete).
const FLASH: &str = r#"{% if let Some(notice) = flash.notice() %}<p class="notice">{{ notice }}</p>{% endif %}
{% if let Some(alert) = flash.alert() %}<p class="alert">{{ alert }}</p>{% endif %}"#;

/// `{{ post.title }}`, or an `if let` for optional values.
fn display(field: &Field, record: &str) -> String {
    let name = &field.name;
    if field.optional {
        format!("{{% if let Some(value) = {record}.{name} %}}{{{{ value }}}}{{% endif %}}")
    } else {
        format!("{{{{ {record}.{name} }}}}")
    }
}

fn index_html(names: &ModelNames, fields: &[Field]) -> String {
    let ModelNames { singular, plural, human_singular, human_plural, .. } = names;
    let lower = human_singular.to_lowercase();
    let headers: String = fields.iter().map(|f| format!("<th>{}</th>", f.label())).collect();
    let cells: String = fields.iter().map(|f| format!("<td>{}</td>", display(f, singular))).collect();
    format!(
        r#"{{% extends "layout.html" %}}

{{% block title %}}{human_plural}{{% endblock %}}

{{% block content %}}
<h1>{human_plural}</h1>
{FLASH}
<p><a href="/{plural}/new">New {lower}</a></p>

<table>
  <thead>
    <tr>{headers}<th></th></tr>
  </thead>
  <tbody>
    {{% for {singular} in {plural} %}}
    <tr>{cells}<td><a href="/{plural}/{{{{ {singular}.id }}}}">Show</a> <a href="/{plural}/{{{{ {singular}.id }}}}/edit">Edit</a></td></tr>
    {{% endfor %}}
  </tbody>
</table>
{{% endblock %}}
"#
    )
}

fn show_html(names: &ModelNames, fields: &[Field]) -> String {
    let ModelNames { singular, plural, human_singular, .. } = names;
    let lower = human_singular.to_lowercase();
    let mut rows = String::new();
    for field in fields {
        writeln!(rows, "  <dt>{}</dt><dd>{}</dd>", field.label(), display(field, singular))
            .expect("writing to a String");
    }
    format!(
        r#"{{% extends "layout.html" %}}

{{% block title %}}{human_singular} {{{{ {singular}.id }}}}{{% endblock %}}

{{% block content %}}
<h1>{human_singular} {{{{ {singular}.id }}}}</h1>
{FLASH}

<dl>
{rows}  <dt>Created at</dt><dd>{{{{ {singular}.created_at }}}}</dd>
  <dt>Updated at</dt><dd>{{{{ {singular}.updated_at }}}}</dd>
</dl>

<p><a href="/{plural}/{{{{ {singular}.id }}}}/edit">Edit</a> · <a href="/{plural}">Back</a></p>

<form action="/{plural}/{{{{ {singular}.id }}}}/delete" method="post" onsubmit="return confirm('Delete this {lower}?')">
  <button type="submit">Delete {lower}</button>
</form>
{{% endblock %}}
"#
    )
}

/// new.html and edit.html: the form tag around `_form.html`.
fn page_html(names: &ModelNames, edit: bool) -> String {
    let ModelNames { plural, human_singular, .. } = names;
    let lower = human_singular.to_lowercase();
    let (title, action, submit, back) = if edit {
        (
            format!("Edit {lower}"),
            format!("/{plural}/{{{{ id }}}}"),
            format!("Update {lower}"),
            format!("/{plural}/{{{{ id }}}}"),
        )
    } else {
        (format!("New {lower}"), format!("/{plural}"), format!("Create {lower}"), format!("/{plural}"))
    };
    format!(
        r#"{{% extends "layout.html" %}}

{{% block title %}}{title}{{% endblock %}}

{{% block content %}}
<h1>{title}</h1>

<form action="{action}" method="post">
{{% include "{plural}/_form.html" %}}
  <button type="submit">{submit}</button>
</form>

<p><a href="{back}">Back</a></p>
{{% endblock %}}
"#
    )
}

/// Error list and one labelled input per field; `form` and `errors` come from
/// the page that includes it.
fn form_fields_html(fields: &[Field]) -> String {
    let mut out = String::from(
        "{% if !errors.is_empty() %}\n  <ul class=\"errors\">\n    {% for error in errors %}<li>{{ error.full_message() }}</li>{% endfor %}\n  </ul>\n{% endif %}\n",
    );
    for field in fields {
        let (name, label) = (&field.name, field.label());
        let required = if field.optional { "" } else { " required" };
        let input = match field.ty {
            FieldType::String => format!(r#"<input name="{name}" value="{{{{ form.{name} }}}}"{required}>"#),
            FieldType::Text => {
                format!(r#"<textarea name="{name}" rows="5"{required}>{{{{ form.{name} }}}}</textarea>"#)
            }
            FieldType::Integer | FieldType::References => {
                format!(r#"<input type="number" step="1" name="{name}" value="{{{{ form.{name} }}}}"{required}>"#)
            }
            FieldType::Float => {
                format!(r#"<input type="number" step="any" name="{name}" value="{{{{ form.{name} }}}}"{required}>"#)
            }
            FieldType::Date => format!(r#"<input type="date" name="{name}" value="{{{{ form.{name} }}}}"{required}>"#),
            FieldType::DateTime => {
                format!(r#"<input type="datetime-local" name="{name}" value="{{{{ form.{name} }}}}"{required}>"#)
            }
            FieldType::Boolean => {
                format!(
                    r#"<input type="checkbox" name="{name}" value="true"{{% if form.{name} %}} checked{{% endif %}}>"#
                )
            }
        };
        writeln!(out, "  <label>{label} {input}</label>").expect("writing to a String");
    }
    out
}
