#!/usr/bin/env python3
"""Generates docs/api-index.md: every public item of the `ocre` crate with its
full path, signature and first doc sentence, grouped by module.

Reads rustdoc's JSON output (nightly only), so it needs the nightly toolchain:

    rustup toolchain install nightly --profile minimal
    python3 scripts/api-index.py           # rewrite docs/api-index.md
    python3 scripts/api-index.py --check   # fail when docs/api-index.md is stale

Signatures are copied from the source spans rustdoc reports, so they read like
the code (and like docs.rs), not like a re-rendered type tree.
"""

import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(ROOT, "docs", "api-index.md")
TARGET = os.path.join(ROOT, "target", "api-index")
KIND_ORDER = ["reexport", "macro", "module", "function", "struct", "enum", "trait", "type_alias", "constant", "static"]
KIND_LABEL = {
    "reexport": "re-export",
    "macro": "macro",
    "module": "mod",
    "function": "fn",
    "struct": "struct",
    "enum": "enum",
    "trait": "trait",
    "type_alias": "type",
    "constant": "const",
    "static": "static",
    "struct_field": "field",
    "variant": "variant",
    "assoc_const": "const",
    "assoc_type": "type",
}
# Trait impls generated by wasm-bindgen or the compiler: noise in an index.
HIDDEN_TRAITS = re.compile(r".*WasmAbi$|^WasmDescribe|^Supports|^TryFromJsValue$|^StructuralPartialEq$")


def rustdoc_json():
    env = dict(os.environ, CARGO_TARGET_DIR=TARGET)
    build = subprocess.run(
        ["cargo", "+nightly", "rustdoc", "-q", "-p", "ocre", "--all-features", "--",
         "-Z", "unstable-options", "--output-format", "json", "--cap-lints", "allow"],
        cwd=ROOT, env=env, capture_output=True, text=True,
    )
    if build.returncode != 0:
        sys.exit(build.stderr)
    with open(os.path.join(TARGET, "doc", "ocre.json")) as file:
        return json.load(file)


_sources = {}


def source_lines(filename):
    if filename not in _sources:
        with open(os.path.join(ROOT, filename)) as file:
            _sources[filename] = file.read().split("\n")
    return _sources[filename]


def signature(item, kind):
    """The item's declaration from its source span, up to its body."""
    span = item["span"]
    if kind == "macro":
        return "macro_rules! " + item["name"]
    lines = source_lines(span["filename"])[span["begin"][0] - 1 : span["end"][0]]
    lines[-1] = lines[-1][: span["end"][1]]
    lines[0] = lines[0][span["begin"][1] - 1 :]
    code = " ".join(line.strip() for line in lines if not line.strip().startswith(("//", "#[")))
    cut, depth = len(code), 0
    for index, char in enumerate(code):
        if kind == "variant":
            break
        if char in "(<[":
            depth += 1
        elif char in ")]" or (char == ">" and code[index - 1] not in "-="):
            depth -= 1
        elif depth == 0 and char in "{;":
            cut = index
            break
    code = re.sub(r"\s+", " ", code[:cut]).strip().rstrip(",;")
    code = code.replace("( ", "(").replace(" )", ")").replace("< ", "<").replace(", >", ">").replace(",)", ")")
    return code


def summary(docs):
    """First sentence of the docs, with intra-doc link targets removed."""
    if not docs:
        return ""
    paragraph = docs.strip().split("\n\n")[0]
    text = " ".join(line.strip() for line in paragraph.split("\n"))
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\[(`[^`]+`)\](?!\()", r"\1", text)
    # The first period that ends a sentence outside a code span (`SELECT 1 ... LIMIT 1`).
    for match in re.finditer(r"(?<!e\.g)(?<!i\.e)\.(\s|$)", text):
        if text.count("`", 0, match.start()) % 2 == 0:
            return text[: match.start() + 1]
    return text


def kind_of(item):
    return next(iter(item["inner"]))


class Index:
    def __init__(self, data):
        self.items = data["index"]
        self.modules = {}
        self.features = {}

    def get(self, item_id):
        return self.items.get(str(item_id))

    def walk(self, module, path):
        """Collects (kind, name, item, feature) per public module path, following `pub use`."""
        entries = self.modules.setdefault("::".join(path), [])
        for item_id in module["inner"]["module"]["items"]:
            item = self.get(item_id)
            kind = kind_of(item)
            name = item["name"]
            gate = feature(item)
            if kind == "use":
                use = item["inner"]["use"]
                target = self.get(use["id"]) if use["id"] is not None else None
                if target is None or target["crate_id"] != 0:
                    entries.append(("reexport", use["name"], item, gate))
                    continue
                item, kind, name = target, kind_of(target), use["name"]
                gate = gate or feature(item)
            if kind == "module":
                self.features["::".join(path + [name])] = gate
                self.walk(item, path + [name])
            if kind in KIND_LABEL:
                entries.append((kind, name, item, gate))

    def members(self, item, kind):
        """Fields, variants, inherent methods and trait methods of a type, and the traits it implements."""
        inner = item["inner"][kind]
        rows, traits = [], []
        if kind == "struct":
            plain = inner["kind"].get("plain")
            tuple_fields = inner["kind"].get("tuple")
            for field_id in (plain["fields"] if plain else tuple_fields or []):
                field = self.get(field_id)
                if field is not None and field["name"] and not field["name"].isdigit():
                    rows.append(("struct_field", field["name"], field))
        if kind == "enum":
            for variant_id in inner["variants"]:
                variant = self.get(variant_id)
                rows.append(("variant", variant["name"], variant))
        if kind == "trait":
            for member_id in inner["items"]:
                member = self.get(member_id)
                rows.append((kind_of(member), member["name"], member))
        for impl_id in inner.get("impls", []):
            impl = self.get(impl_id)["inner"]["impl"]
            if impl["is_synthetic"] or impl["blanket_impl"] is not None:
                continue
            if impl["trait"] is None:
                for member_id in impl["items"]:
                    member = self.get(member_id)
                    # Items generated by attribute macros (`#[durable_object]`) have no source of their own.
                    if member["visibility"] == "public" and signature(member, kind_of(member)):
                        rows.append((kind_of(member), member["name"], member))
            elif not HIDDEN_TRAITS.match(impl["trait"]["path"].split("::")[-1]):
                traits.append(impl["trait"]["path"].split("::")[-1])
        return rows, sorted(set(traits))


def feature(item):
    """The cargo feature an item is gated on (`#[cfg(feature = "...")]`), if any."""
    for attr in item.get("attrs", []):
        text = attr if isinstance(attr, str) else json.dumps(attr)
        match = re.search(r'feature\\?"?,? value: Some\(\\?"(\w+)|feature = \\?"(\w+)', text)
        if match:
            return match.group(1) or match.group(2)
    return None


def entry(path, kind, item, gate=None):
    line = f"- `{path}` ({KIND_LABEL[kind]}{f', feature `{gate}`' if gate else ''})"
    text = summary(item.get("docs"))
    if text:
        line += f": {text}"
    if kind == "reexport":
        line += f"\n  `pub use {item['inner']['use']['source']}`"
    elif kind != "module" and item.get("span"):
        code = signature(item, kind)
        if kind == "struct" and None in (item["inner"]["struct"]["kind"].get("tuple") or []):
            # Tuple structs with private fields: show the shape, not the private types.
            code = code[: code.index("(")] + "(/* private fields */)"
        line += f"\n  `{code}`"
    return line


def render(data):
    index = Index(data)
    index.walk(index.get(data["root"]), ["ocre"])
    out = [
        "# Ocre API index",
        "",
        "Every public item of the `ocre` crate (all features) with its path, signature and",
        "first doc sentence, grouped by module. Full documentation: the rustdoc pages, or",
        "`cargo doc -p ocre --all-features --open`.",
        "",
        "Generated by `python3 scripts/api-index.py` from rustdoc JSON; do not edit by hand.",
    ]
    for module_path in sorted(index.modules, key=lambda path: (path != "ocre", path)):
        entries = index.modules[module_path]
        gate = index.features.get(module_path)
        out += ["", f"## `{module_path}`" + (f" (feature `{gate}`)" if gate else ""), ""]
        entries.sort(key=lambda entry: (KIND_ORDER.index(entry[0]), entry[1]))
        for kind, name, item, gate in entries:
            path = f"{module_path}::{name}"
            out.append(entry(path, kind, item, gate))
            if kind in ("struct", "enum", "trait"):
                rows, traits = index.members(item, kind)
                for member_kind, member_name, member in rows:
                    out.append("  " + entry(f"{path}::{member_name}", member_kind, member).replace("\n", "\n  "))
                if traits:
                    out.append("  - Implements: " + ", ".join(f"`{name}`" for name in traits))
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    text = render(rustdoc_json())
    if check:
        current = open(OUTPUT).read() if os.path.exists(OUTPUT) else ""
        if current != text:
            sys.exit("docs/api-index.md is stale: run `python3 scripts/api-index.py`")
        return
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as file:
        file.write(text)


if __name__ == "__main__":
    main()
